### ISSUE TITLE
Suggestions de compléments

### ISSUE THREAD

**Issue by ericemc3** [ljegou/geotests#9]
Données sociales, sur l’emploi et de santé
=========================================
Sirse : base de données socio-sanitaires et environnementales territorialisée
https://sirse.atlasante.fr

Atlas de la santé mentale
https://santementale.atlasante.fr

CAF
http://data.caf.fr/site/

Données culturelles
====================
Observatoire de la lecture publique
https://olp.culture.fr

Données admin., financières et fiscales
======================================
Observatoire des finances et de la gestion publique locales
https://data.ofgl.fr/explore/?exclude.theme=INTERNE&sort=title

Agriculture
===========
https://vizagreste.agriculture.gouv.fr/

Occitanie
=========
Observatoire de l'AU de Nîmes
http://observatoire.audrna.com/

Observatoire des fragilités Grand Sud (Carsats)
https://www.observatoires-fragilites-grand-sud.fr

Observatoire du Gers
https://observatoire.gers.fr

Divers
======
​Observatoire des Territoires du CGET : CGET est désormais ANCT
RGP Insee : RGP n'est plus la bonne dénomination (nostalgie) => recensement de la population
Consommation de la consommation / production de soins => Cartographie de la consommation / production de soins

**Comment by ljegou** [comment]
Merci Éric pour ces suggestions, je vais les intégrer.

**Comment by ericemc3** [comment]
Avec plaisir Laurent, et merci pour cette belle sélection, qui me rend bien service par ailleurs pour répondre à un besoin concret
